### PR TITLE
Don't issue Range past EOF, when HTTPFile size known

### PR DESCRIPTION
**Pull request by martindurant**
Fixes https://github.com/dask/dask/issues/5186

### CODE REVIEW

**Comment by martindurant** [comment]
@mrocklin , I promise to make a real test HTTP server for testing in the near future, more than the limited capabilities of python's `http.server` executable.

**Comment by mrocklin** [comment]
I can imagine that you'll have better things to do, especially in a few
months :)

**Comment by martindurant** [comment]
(s3fs temporarily failing due to moto update, ignoring https://github.com/dask/s3fs/pull/209#issuecomment-516888832 )

**Comment by mrocklin** [comment]
Thanks @martindurant .  Is it possible to push out a bugfix release?

**Comment by martindurant** [comment]
Yes, is building now

**Pull request merged**
