### PR TITLE
Implement chained URLs

### PR DESCRIPTION
**Pull request by martindurant**
@TomAugspurger : the API for calling s3 via a dask worker is like

```
dd.read_csv("dask://localhost:8786::s3://bucket/path/*.csv", storage_options={'s3': {'anon': True}})
```

Obviously needs more testing...

### CODE REVIEW

**Comment by martindurant** [comment]
Ref: https://github.com/dask/dask/pull/6011

**Comment by martindurant** [comment]
@TomAugspurger , thoughts on auto_mkdir here, as requires by pyarrow? It would be nice to avoid the warning showing up, but I'm not certain what the default value should be; we certainly don't want to break arrow usage of fsspec.

**Comment by TomAugspurger** [comment]
I think auto_mkdir is unnecessary after https://github.com/intake/filesystem_spec/pull/211. So it should be fine to make that change, but I'd recommend doing it in its own PR.

---

Did you think at all about making the protocol `dask-s3fs://` rather than `dask:...:s3fs:://``? I haven't looked closely at the implementation, but I'm wondering if that would simplify things. Ideally this would be just another backend, and would require changes in core and spec?

**Comment by martindurant** [comment]
`dask-s3fs://` wouldn't allow you to encode extra path parts into the URL, like the example with including the dask client address, or where you want to access some file(s) within a zip (there is a test for "simplecache::zip://*::file://filepath", which extracts files to the cache from the target file, which could have been remote)

**Comment by TomAugspurger** [comment]
Do you think that encoding things like the scheduler address in the URL is a good idea? My initial reaction is that would would fall more naturally under a `storage_args` (with a default of getting a global client, so it shouldn't be necessary).

**Comment by martindurant** [comment]
both work

**Pull request merged**
