### PR TITLE
Add `cache_options` to AbstractFileSystem._open subclasses

### PR DESCRIPTION
**Pull request by TomAugspurger**
Confirmed that the dask HDFS tests are passing with this.

See https://github.com/intake/filesystem_spec/issues/201 for more work to be done along this line.

Closes https://github.com/intake/filesystem_spec/issues/198

cc @jrbourbeau

### CODE REVIEW

**Comment by martindurant** [comment]
Can you also please check what happens for file types *not* based on AbstractBufferedFile? I can see that `SFTPFileSystem._open()` discards unused kwargs, for instance, so that's OK.

**Comment by TomAugspurger** [comment]
I think HDFSFile is another example.

Is there a reason these *don't* return subclasess of AbstractBufferedFile? I think having `AbstractFileSystem.open` return a common type for all subclasess would be helpful.

**Comment by martindurant** [comment]
You could, if you were prepared to write wrappers to pass on calls to the original file object. The implementation of [local files](https://github.com/intake/filesystem_spec/blob/master/fsspec/implementations/local.py#L159) does this partially and might be a decent guide. There are corner cases though: http returns a stream-only (no seek) requests file-like object in the case of block_size=0 - that would need to be wrapped too.

**Comment by martindurant** [comment]
Short story: I agree it might be nice, but involves some work.

**Pull request merged**
