### PR TITLE
Added adl protocol to registry.py, and added lowercasing to isdir() a…

### PR DESCRIPTION
**Pull request by hayesgb**
Wanted to get started with the Azure Datalake Gen1 implementation.  I've added adl to registry.py, with error instructions to install the adlfs library currently located in my repository.  I will create a pip installable over the next few days for that, and then begin adding tests.  The only changes implemented here are to the registry.py file, and lowercasing of the returns from the isfile and isdir method calls in core.py.  This is needed because the response of an info() call from Azure is all-caps, which returns an error with core.py as written.

### CODE REVIEW

**Comment by martindurant** [comment]
Hi, what is the status of this, at the moment? With the lower() operation, dod you manage to get things working with adlfs? I know that I made comments on your fork, but it would be nice to come to both a long-term plan and a quicker solution that would enable dask and azure-datalake to work together.

**Comment by hayesgb** [comment]
By adding the .lower() change, and adding adl to the registry, the adlfs (not dask-adlfs) is working with Gen1 Datalake on Azure.  I’m currently working on adding a second class to the adlfs package that will interface with Gen2.  Once I have those working, then I’ll start adding tests and improving usability.

**Comment by martindurant** [comment]
Would it be possible to move the lower() call into the external code rather than having it here in fsspec itself?

**Comment by hayesgb** [comment]
I can probably just reimplement the method calls in adlfs.  However, will fsspec pick up the package if it’s not listed in fsspec’s registry.py file?

**Comment by martindurant** [comment]
> will fsspec pick up the package if it’s not listed in fsspec’s registry.py

No, this is exactly the right thing to do. If you are still experimental/testing, you can edit `fsspec.registry` directly at runtime.

**Pull request closed without merging**
