### PR TITLE
More concrete around ioloops and threads

### PR DESCRIPTION
**Pull request by martindurant**
@rabernat @jmcgrath207 @rsignell-usgs @zflamig

Would appreciate running your sometimes-hanging workflows with this PR.

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
Should we try this with `pip install git+https://github.com/martindurant/s3fs` as well?

**Comment by martindurant** [comment]
You will need the specific branch 
```
pip install git+https://github.com/martindurant/filesystem_spec@ioloop_massage
```
(note that this is installing fsspec, not s3fs)

**Comment by zflamig** [comment]
When trying this I am getting this error now.

```
TypeError                                 Traceback (most recent call last)
<ipython-input-13-f76853d87372> in <module>
----> 1 temp_mean = temp_mean.compute()

~/anaconda3/envs/daskpy3/lib/python3.7/site-packages/xarray/core/dataarray.py in compute(self, **kwargs)
    891         """
    892         new = self.copy(deep=False)
--> 893         return new.load(**kwargs)
    894 
    895     def persist(self, **kwargs) -> "DataArray":

~/anaconda3/envs/daskpy3/lib/python3.7/site-packages/xarray/core/dataarray.py in load(self, **kwargs)
    865         dask.array.compute
    866         """
--> 867         ds = self._to_temp_dataset().load(**kwargs)
    868         new = self._from_temp_dataset(ds)
    869         self._variable = new._variable

~/anaconda3/envs/daskpy3/lib/python3.7/site-packages/xarray/core/dataset.py in load(self, **kwargs)
    739 
    740             # evaluate all the dask arrays simultaneously
--> 741             evaluated_data = da.compute(*lazy_data.values(), **kwargs)
    742 
    743             for k, data in zip(lazy_data, evaluated_data):

~/anaconda3/envs/daskpy3/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    559         postcomputes.append(x.__dask_postcompute__())
    560 
--> 561     results = schedule(dsk, keys, **kwargs)
    562     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    563 

~/anaconda3/envs/daskpy3/lib/python3.7/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2682                     should_rejoin = False
   2683             try:
-> 2684                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2685             finally:
   2686                 for f in futures.values():

~/anaconda3/envs/daskpy3/lib/python3.7/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1997                 direct=direct,
   1998                 local_worker=local_worker,
-> 1999                 asynchronous=asynchronous,
   2000             )
   2001 

~/anaconda3/envs/daskpy3/lib/python3.7/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    838         else:
    839             return sync(
--> 840                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    841             )
    842 

~/anaconda3/envs/daskpy3/lib/python3.7/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    338     if error[0]:
    339         typ, exc, tb = error[0]
--> 340         raise exc.with_traceback(tb)
    341     else:
    342         return result[0]

~/anaconda3/envs/daskpy3/lib/python3.7/site-packages/distributed/utils.py in f()
    322             if callback_timeout is not None:
    323                 future = asyncio.wait_for(future, callback_timeout)
--> 324             result[0] = yield future
    325         except Exception as exc:
    326             error[0] = sys.exc_info()

~/anaconda3/envs/daskpy3/lib/python3.7/site-packages/tornado/gen.py in run(self)
    760 
    761                     try:
--> 762                         value = future.result()
    763                     except Exception:
    764                         exc_info = sys.exc_info()

~/anaconda3/envs/daskpy3/lib/python3.7/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1856                             exc = CancelledError(key)
   1857                         else:
-> 1858                             raise exception.with_traceback(traceback)
   1859                         raise exc
   1860                     if errors == "skip":

/opt/conda/lib/python3.7/site-packages/dask/array/core.py in getter()

/opt/conda/lib/python3.7/site-packages/numpy/core/_asarray.py in asarray()

/opt/conda/lib/python3.7/site-packages/xarray/core/indexing.py in __array__()

/opt/conda/lib/python3.7/site-packages/numpy/core/_asarray.py in asarray()

/opt/conda/lib/python3.7/site-packages/xarray/core/indexing.py in __array__()

/opt/conda/lib/python3.7/site-packages/numpy/core/_asarray.py in asarray()

/opt/conda/lib/python3.7/site-packages/xarray/core/indexing.py in __array__()

/opt/conda/lib/python3.7/site-packages/numpy/core/_asarray.py in asarray()

/opt/conda/lib/python3.7/site-packages/xarray/coding/variables.py in __array__()

/opt/conda/lib/python3.7/site-packages/xarray/coding/variables.py in _apply_mask()

/opt/conda/lib/python3.7/site-packages/numpy/core/_asarray.py in asarray()

/opt/conda/lib/python3.7/site-packages/xarray/core/indexing.py in __array__()

/opt/conda/lib/python3.7/site-packages/xarray/backends/h5netcdf_.py in __getitem__()

/opt/conda/lib/python3.7/site-packages/xarray/core/indexing.py in explicit_indexing_adapter()

/opt/conda/lib/python3.7/site-packages/xarray/backends/h5netcdf_.py in _getitem()

/opt/conda/lib/python3.7/site-packages/h5netcdf/core.py in __getitem__()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

/opt/conda/lib/python3.7/site-packages/h5py/_hl/dataset.py in __getitem__()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5d.pyx in h5py.h5d.DatasetID.read()

h5py/_proxy.pyx in h5py._proxy.dset_rw()

h5py/h5fd.pyx in h5py.h5fd.H5FD_fileobj_read()

/opt/conda/lib/python3.7/site-packages/fsspec/spec.py in readinto()

/opt/conda/lib/python3.7/site-packages/fsspec/spec.py in read()

/opt/conda/lib/python3.7/site-packages/fsspec/caching.py in _fetch()

TypeError: 'NoneType' object is not subscriptable
```

**Comment by martindurant** [comment]
Would you mind trying again now? 
I also made new branch ioloop_massage2 with a different approach.

**Comment by martindurant** [comment]
Probably my fork, master; although the changes here are orthogonal to what I was doing there, so master on dask/s3fs.git should work as well

**Comment by zflamig** [comment]
`ioloop_massage2` looks good. I was able to complete a computation that was stalling pretty much 100% of the time before. Will let the others chime in if its working for their use cases too now. I'm running with s3fs 0.5.2.

**Pull request closed without merging**
