### PR TITLE
ci: run py36 on the github actions

### PR DESCRIPTION
**Pull request by isidentical**

### CODE REVIEW

**Comment by isidentical** [comment]
Oh, I thought 3.6 was already supported (judging by the classifiers) but apparently it is not; https://github.com/intake/filesystem_spec/pull/522. This might be a dead cause

**Comment by martindurant** [comment]
You would need to change `python_requires=` in setup.py to get the CI to run. The classifiers have not been updates since the last release.

**Comment by isidentical** [comment]
> You would need to change python_requires= in setup.py to get the CI to run.

Yes, I am aware. I thought it was the `3.6>=` before I made the PR, and I am a bit confused now regarding the official status of support.

**Comment by isidentical** [comment]
Apparently all tests pass, though pyarrow seems to be a bit problematic when installed in <1, is there anything I should be aware when bumping it to 1>=?

**Comment by martindurant** [comment]
Do you mean pyarrow -> v>1.0? That should be OK. The HDFS implementation is slated to be dropped, but not yet.

**Comment by isidentical** [comment]
yep

**Comment by martindurant** [comment]
OK, thanks for doing this - let's keep py36 alive a little longer!

**Comment by isidentical** [comment]
Thanks @martindurant!

**Pull request merged**
