### PR TITLE
Add wandb implementation

### PR DESCRIPTION
**Pull request by jkulhanek**

### CODE REVIEW

**Comment by martindurant** [comment]
Thanks for contributing and for writing a new implementation!
What is wandb? I'd love to see some examples on your repo.

**Comment by jkulhanek** [comment]
Wandb [https://docs.wandb.ai/](https://docs.wandb.ai/) is a machine learning tool which tracks your experiments. While the experiment is running, it tracks its metrics and helps you visualize the progress. You can also upload files such as configuration files, models, datasets (some files are uploaded automatically). After the experiment is finished, you can access the experiment's files (only read-only).

The implementation I wrote allows researchers who use wandb to access the finished experiment's files using the fsspec interface. I know a lot of researchers who (like me) have some models stored locally, some on ssh or gcloud and some on wandb and I thought that this implementation might be useful for them.

I already have some examples in my repo (opening a file and listing files). What other examples would you like me to add?

**Comment by martindurant** [comment]
Sounds a little bit like [rubicon](https://github.com/capitalone/rubicon-ml) perhaps? (cc @ryanSoley , @mmccarty ).

You might want to add that description to your README :). 

I don't know if you have any interaction with the wandb team; if not, you may wish to let them know you have this interface.

**Comment by jkulhanek** [comment]
Ok, I will update the README. From what I understand, rubicon stores files locally (or on S3), while wandb stores them on their own servers. I will notify the wandb team.

**Comment by martindurant** [comment]
👍  This is merged, docs will update soon.

**Comment by jkulhanek** [comment]
Thank you!

**Pull request merged**
