### PR TITLE
Add cache timeout and directory cache

### PR DESCRIPTION
**Pull request by TomAugspurger**
Closes https://github.com/intake/filesystem_spec/issues/215

WIP for now, I need to incorporate https://github.com/intake/filesystem_spec/issues/215#issuecomment-561357180.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
@martindurant  Is there a standard schema for what entries in DirCache should look like? I see that `github` and `ftp` use them. In fsspec/spec.py, it's only used in `_ls_from_cache`, which seems to expect something like

```
{
    "path": {
        "name": name,
    }
} 
```

Standardizing the structure here would be good (maybe in a dataclass?), but I'm not sure what all to include yet.

**Comment by TomAugspurger** [comment]
For `ftp`, elements of DirCache are `List[Tuple[str, Dict]]`, where the first item of the tuple is the path of the element, and the dict has a schema like `modify, perm, size, file, unique, name`.

```python
(Pdb) pp out[:2]
[('__init__.py',
  {'modify': '20190813183127',
   'name': '/__init__.py',
   'perm': 'r',
   'size': 0,
   'type': 'file',
   'unique': '1000004g2058413d7'}),
 ('__pycache__',
  {'modify': '20191127162327',
   'name': '/__pycache__',
   'perm': 'el',
   'size': 0,
   'type': 'dir',
   'unique': '1000004g206bad42b'})]
```

those are all the files under the path (the key).

For `github` we just have a `List[Dict]`, and the keys in the dict are `name, mode, type, size, sha`. 

These are inconsistent. At the moment, I'm leaning toward a namedtuple structure like

```python
CacheItem = namedtuple("CacheItem", ["name", "details"])
```

where `name` is a string, and `details` is a dict with anything. Hopefully that will suffice.

**Comment by martindurant** [comment]
The canonical structure should be:

```
{'cached_path`: [
    {"name": 'file_path", 
     "size": 10,
     "type": "file"},
    ...
   ]
}
```
The FTP case is clearly based on the output of the client library, and ought to be processed into canonical form, as it done for s3, gcs...

**Comment by martindurant** [comment]
i.e., the key is the path that we did a listing for

**Comment by martindurant** [comment]
This still looks useful to me

**Comment by martindurant** [comment]
Superceded by #243

**Pull request closed without merging**
