### PR TITLE
Raise low-level program friendly OSError.

### PR DESCRIPTION
**Pull request by xyb**
for example, fuse.

### CODE REVIEW

**Comment by martindurant** [comment]
Do you think any of the tests should explicitly look for these errors?

**Comment by xyb** [comment]
@martindurant Sure, actually the FUSE test runs into an error, but pytest catches it so you wont see it. And on my OSX system, the same error blocks pytest for about 2 minutes, so I must kill it to stop the testing process. If you pass `-s` to pytest, you will find it:
```
$ pytest -s fsspec/tests/test_fuse.py
============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-6.0.2, py-1.9.0, pluggy-0.13.1
rootdir: /home/xieyanbo/filesystem_spec
collected 1 item

fsspec/tests/test_fuse.py Traceback (most recent call last):
  File "/home/xieyanbo/filesystem_spec/venv/lib/python3.6/site-packages/fuse.py", line 734, in _wrapper
    return func(*args, **kwargs) or 0
  File "/home/xieyanbo/filesystem_spec/venv/lib/python3.6/site-packages/fuse.py", line 796, in rmdir
    return self.operations('rmdir', path.decode(self.encoding))
  File "/home/xieyanbo/filesystem_spec/venv/lib/python3.6/site-packages/fuse.py", line 1076, in __call__
    return getattr(self, op)(*args)
  File "/home/xieyanbo/filesystem_spec/fsspec/fuse.py", line 54, in rmdir
    self.fs.rmdir(path)
  File "/home/xieyanbo/filesystem_spec/fsspec/implementations/memory.py", line 105, in rmdir
    raise OSError("Directory %s not empty" % path)
OSError: Directory /mounted/test not empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xieyanbo/filesystem_spec/venv/lib/python3.6/site-packages/fuse.py", line 737, in _wrapper
    if e.errno > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/home/xieyanbo/filesystem_spec/venv/lib/python3.6/site-packages/fuse.py", line 756, in _wrapper
    self.__critical_exception = e
NameError: name 'self' is not defined
fuse: bad error value: 1
.

============================== 1 passed in 1.03s ===============================
```

**Comment by xyb** [comment]
@martindurant I'm working on adding more tests to FUSE test.

**Comment by xyb** [comment]
Hmmm, it looks like the webhdfs test is unstable:
- https://travis-ci.org/github/intake/filesystem_spec/jobs/729510169
But I've triggered a rerun of the test by forcing the last commit to be updated.

**Comment by martindurant** [comment]
The webhdfs tests have been stable for quite a while. It looks like docker failed here, perhaps fetching the image was slow.

**Comment by martindurant** [comment]
PS: fuse on macOS is often problematic. I don't really know how useful fuse is to people, given the limitations of mapping possibly not-very-posix backends.

**Pull request merged**
