### PR TITLE
Fix for gcsfs protocol which is tuple

### PR DESCRIPTION
**Pull request by elephantum**

### CODE REVIEW

**Comment by martindurant** [comment]
`_strip_protocol` should already deal with this, I don't suppose that the code is ever reached. You could check this with simple print/pdb.

**Comment by elephantum** [comment]
@martindurant I did this change because of the actual problem I had while chaining FS's.

```
GCSFS = fsspec.filesystem('gcs')

FS = fsspec.filesystem(
    "filecache", 
    target_protocol=GCSFS, 
)

FS.open('somefile')
```

This code fails on the latest release of filespec and my PR fixes it.

**Comment by martindurant** [comment]
OK, right got it - I thought this was the other way around.
The PR fails lint, but otherwise looks good.

**Comment by elephantum** [comment]
@martindurant fixed formatting

**Comment by martindurant** [comment]
Thank you!

**Pull request merged**
