### PR TITLE
Faster references, git URL fix

### LINKED ISSUE #809: get_fs_token_paths doesnt use path from git:// uri
When `get_fs_token_paths` is used with `"git://<some_local_path>"`, it should return an instance of `GitFileSystem` in that local path. But `_get_kwargs_from_urls` of that class does not extract `path` option from uri, so when the [class is instantiated later inside `get_fs_token_paths`](https://github.com/intake/filesystem_spec/blob/da89f163c94d17deacbe2cecfc37e20009580573/fsspec/core.py#L640), the `options` dict is empty, and default value for `path` is used, which is `os.getcwd` (and also wrong if uri was not just `"git://"`). And if there is no git repo in cwd, an exception is raised.
One-liner to reproduce:
`mkdir aaa && cd aaa && git init && cd ../ && python -c "from fsspec import get_fs_token_paths; get_fs_token_paths('git://aaa')"`

### PR DESCRIPTION
**Pull request by martindurant**
Fixes #809

### CODE REVIEW

**Comment by martindurant** [comment]
@mike0sv : the correct invocation is with a URL
```
get_fs_token_paths("git://myfile::file://local_git")
```
i.e., find the file `myfile` within the repo at local path `local_git`. I do not believe `pygit` can be persuaded to work with anything other than local paths, but still. Feel free to suggest alternate ways to encode the repo location and starting hash (and see the example of the github implementation).

**Comment by mike0sv** [comment]
Maybe just look for `.git` dir in `path`, `os.path.dirname(path)`,  `os.path.dirname(os.path.dirname(path))` until we find it? Then it will be `path` for pygit, and the rest (path relative to git root) we can return as `paths`

**Comment by mike0sv** [comment]
Also, when I first saw that fsspec supports git filesystem, I thought it supports everything from here https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols, but I guess this is another big topic

**Comment by martindurant** [comment]
> Maybe just look for .git dir in path, os.path.dirname(path), os.path.dirname(os.path.dirname(path)) until we find it?

git will already look in the parents, that's not my question. I am asking for suggestions of how you would expect to partition the "location of the git repo" from "location of a file within the repo" in a single URL. I have given a form that works now, as of this URL.

**Comment by mike0sv** [comment]
Yes, I propose to just find it before providing to `pygit`. For example, for URL `git://some/path/to/git_repo_root_here/some/path/inside/repo` it will yield `fs=GitFileSystem(path="some/path/to/git_repo_root_here"), token=...,paths=["some/path/inside/repo"]`. Rev could be provided maybe like `git://rev@...` or `git://rev::...`

**Comment by martindurant** [comment]
@mike0sv , see the GitFileSystem docstring for my proposed compromise.

**Comment by mike0sv** [comment]
I am still convinced that what I am proposing is easier and cleaner. Am I missing something here?
Also, I think in your solution it makes more sense to use `git://<rev>@<repo>::<path>`, than `git://<rev>@<path>::<repo>`

**Comment by martindurant** [comment]
Docstring:

> may be of the form
> "git://[path-to-repo[:]][ref@]path/to/file" (but the actual
> file path should not contain "@" or ":").

The thing with "::" is general across fsspec and not very relevant to git, which only works with local paths.

**Comment by mike0sv** [comment]
Yes, but in tests its still
```python
    fs, _, paths = fsspec.core.get_fs_token_paths(f"git://file1::file://{d}")
    assert make_path_posix(d) in make_path_posix(fs.repo.path)
    assert paths == ["file1"]
```
Or you just didn't implement this yet?
Still, you can just extract fo from regular local path like this `git://rev@local_path` -> strip protocol, split by @ -> `options['fo'] = Repository(local_path).workdir, paths = [os.path.relpath(...)]`. Without separately specifying repo path

**Comment by martindurant** [comment]
> you can just extract fo from regular local path like

With which API are you expecting to use this? 

I added the newer alternate URL type to the same test.

**Comment by martindurant** [comment]
I'm putting this in now, but we can still iterate on the best spelling for git URLs afterwards.

**Pull request merged**
