### PR TITLE
Allow returning details from find/walk/glob

### LINKED ISSUE #214: Shouldn't 'walk' return 'info' instead of just name?
Have been working on a tiny wrapper (mostly put/get functionality, no need of _open) around [Google Drive](https://developers.google.com/drive/api/v3/about-sdk) - _gdrivefs_.

One thing I noticed is that _walk_ doesn't return the object infos. Is there a reason for this?

In my case this will double the necessary remote calls to retrieve the file info. Hence, I don't want to use the provided _walk_, so if it's not going to change (to provide a fourth array with the infos) - I will overwrite it in _gdrivefs_.

If you are wondering in what context I need this - I am porting [a cloud storage sync application](https://github.com/ivannp/cync) from C# to Python. In the process, I came across fsspec and decided it to use it - very nice and has similar functionality to the fs abstraction I have in my project.

### PR DESCRIPTION
**Pull request by dhirschfeld**
This is a slightly different take on #116

----
Closes #116 
Resolves #214

### CODE REVIEW

**Comment by dhirschfeld** [comment]
In the case of `find` the return type is `Iterable[filename]` however in the case that `detail=True` the iterable is a dict with the value being the info dict:
```python
In [8]: fs.find('/tmp')
Out[8]: 
['/tmp/DELETEME-01.csv',
 '/tmp/DELETEME-04.csv',
 '/tmp/tmp2/DELETEME-02.csv',
 '/tmp/tmp2/DELETEME-03.csv']

In [9]: fs.find('/tmp', detail=False) == list(fs.find('/tmp', detail=True))
Out[9]: True

In [10]: list(fs.find('/tmp', detail=True))
Out[10]: 
{
    '/tmp/DELETEME-01.csv': {
        'modify': '20200123234738',
        'name': '/tmp/DELETEME-01.csv',
        'size': 32109,
        'type': 'file',
        'unix.mode': '0644'
    },
    '/tmp/DELETEME-04.csv': {
        'modify': '20200123234901',
        'name': '/tmp/DELETEME-04.csv',
        'size': 32123,
        'type': 'file',
        'unix.mode': '0644'
    },
    '/tmp/tmp2/DELETEME-02.csv': {
        'modify': '20200123234742',
        'name': '/tmp/tmp2/DELETEME-02.csv',
        'size': 32123,
        'type': 'file',
        'unix.mode': '0644'
    },
    '/tmp/tmp2/DELETEME-03.csv': {
        'modify': '20200123234847',
        'name': '/tmp/tmp2/DELETEME-03.csv',
        'size': 32123,
        'type': 'file',
        'unix.mode': '0644'
    }
}
```

**Comment by dhirschfeld** [comment]
Looks like the leading `/` is being stripped. Will investigate...
```
    def test_1(m):
        m.touch("/somefile")  # NB: is found with or without initial /
        m.touch("afiles/and/anothers")
>       assert m.find("") == ["afiles/and/anothers", "somefile"]
E       AssertionError: assert ['/somefile',...and/anothers'] == ['afiles/and/...', 'somefile']
E         At index 0 diff: '/somefile' != 'afiles/and/anothers'
E         Full diff:
E         - ['/somefile', 'afiles/and/anothers']
E         + ['afiles/and/anothers', 'somefile']
```

**Comment by dhirschfeld** [comment]
Example of the new `walk` api:
```python
In [11]: list(fs.walk('/tmp'))
Out[11]: 
[('/tmp', ['tmp2'], ['DELETEME-01.csv', 'DELETEME-04.csv']),
 ('/tmp/tmp2', [], ['DELETEME-02.csv', 'DELETEME-03.csv'])]

In [12]: list(fs.walk('/tmp', detail=True))
Out[12]: 
[('/tmp',
  {'tmp2': {'type': 'directory',
    'modify': '20200123234847',
    'unix.mode': '0755',
    'name': '/tmp/tmp2',
    'size': 0}},
  {'DELETEME-01.csv': {'type': 'file',
    'size': 32109,
    'modify': '20200123234738',
    'unix.mode': '0644',
    'name': '/tmp/DELETEME-01.csv'},
   'DELETEME-04.csv': {'type': 'file',
    'size': 32123,
    'modify': '20200123234901',
    'unix.mode': '0644',
    'name': '/tmp/DELETEME-04.csv'}}),
 ('/tmp/tmp2',
  {},
  {'DELETEME-02.csv': {'type': 'file',
    'size': 32123,
    'modify': '20200123234742',
    'unix.mode': '0644',
    'name': '/tmp/tmp2/DELETEME-02.csv'},
   'DELETEME-03.csv': {'type': 'file',
    'size': 32123,
    'modify': '20200123234847',
    'unix.mode': '0644',
    'name': '/tmp/tmp2/DELETEME-03.csv'}})]

In [13]: [(path, list(dirs), list(files)) for path, dirs, files in fs.walk('/tmp', detail=True)] == list(fs.walk('/tmp'))
Out[13]: True
```

By default it's the same as previously but if `detail=True` then dictionaries are returned keyed by name with the value being the info dict. Previously, if `detail` was passed as a kwarg it raised an exception:
```python
TypeError: ls() got multiple values for argument 'detail'
```

**Comment by dhirschfeld** [comment]
@martindurant - let me know what you think of this proposed api. 

By default everything is the same but it allows the user to provide `detail=True` to instead return dictionaries. Implementing it like this allows code which simply iterates over the results to work irrespective of whether `detail` is True or False:
```python
In [14]: for file in fs.find('/tmp', detail=False):
    ...:     print(file)
    ...:     
/tmp/DELETEME-01.csv
/tmp/DELETEME-04.csv
/tmp/tmp2/DELETEME-02.csv
/tmp/tmp2/DELETEME-03.csv

In [15]: for file in fs.find('/tmp', detail=True):
    ...:     print(file)
    ...:     
/tmp/DELETEME-01.csv
/tmp/DELETEME-04.csv
/tmp/tmp2/DELETEME-02.csv
/tmp/tmp2/DELETEME-03.csv
```

**Comment by dhirschfeld** [comment]
If you're happy with the api I can think about adding a couple of tests...

**Comment by martindurant** [comment]
Yes, looks good.

**Comment by dhirschfeld** [comment]
Hmm, seems to work for me  🤔
 
image


...ugh, py35 fails because I rely on dictionary ordering.

**Comment by dhirschfeld** [comment]
This introduces python version-dependent behaviour. Since dicts aren't ordered in py<36 the order of returned files isn't guaranteed on py35.

It looks like some effort (using `sorted`) was previously made to guarantee the order of returned files, however I think this is an acceptable regression (for py35) given [`NEP-29`](https://numpy.org/neps/nep-0029-deprecation_policy.html) and the fact that most of the rest of the scientific-python ecosystem has already dropped py35 

***xref:*** https://github.com/intake/filesystem_spec/issues/179#issuecomment-553522907

**Comment by dhirschfeld** [comment]
@martindurant - I think this is ready to go (pending any further feedback!)

**Comment by martindurant** [comment]
Great, thank you!

**Comment by pvanderlinden** [comment]
Are any plans in releasing fsspec? The last release has been almost three months ago. It would be great to be able to use these improvements

**Comment by martindurant** [comment]
Agreed, I'll put it on my list.

**Comment by pvanderlinden** [comment]
Thanks!

**Pull request merged**
