### PR TITLE
Make CI linting identical to pre-commit hooks linting

### PR DESCRIPTION
**Pull request by andersy005**
Addresses @martindurant's comment in https://github.com/intake/filesystem_spec/pull/533#issuecomment-776070058

### CODE REVIEW

**Comment by martindurant** [comment]
That's a lot of changes!

**Comment by andersy005** [comment]
> That's a lot of changes! 

:) Should be fixed now.

**Comment by martindurant** [comment]
The failing test is touching an external network endpoint for ftp find, where the contents seem to have changed. The test should be removed, or changed to a set of `in` asserts rather than exact output equality.

**Comment by andersy005** [comment]
> The test should be removed, or changed to a set of in asserts rather than exact output equality. 

Do you want these fixed in this PR?

**Comment by martindurant** [comment]
Yes please, if you have the time

**Pull request merged**
