### PR TITLE
WIP: TAR FS

### PR DESCRIPTION
**Pull request by martindurant**
cc #297 
@kmpaul , please have a go!

### CODE REVIEW

**Comment by kmpaul** [comment]
Will do!

**Comment by kmpaul** [comment]
@martindurant Thanks for getting this started, but I just got swamped with other work last week.  It might be a week or two before I can get to this.  I hope that's okay.  But I really do appreciate you getting this started.

**Comment by martindurant** [comment]
I don't think there's any rush here. If someone appears desperately in search of a tar FS, well they can experiment with this one.

**Comment by martindurant** [comment]
@kmpaul , have you had any success with this implementation?

**Comment by kmpaul** [comment]
I haven't had any time. I've just been swamped, and I'm still trying to dig myself out. If you think this needs to move forward, and you have someone else to look into it, I won't be offended.

**Comment by martindurant** [comment]
> I won't be offended.

:) No problem, I might just ping you again in a month or so!
If anyone happens to look for this functionality, a search should lead them here.

**Comment by kmpaul** [comment]
Thank you!  And thank you for keeping me honest.  I don't want this to completely get lost.

**Comment by martindurant** [comment]
Note that #446 implements tar-file reading. It does not have indexing, so the code here might still be useful, but, it seems, not urgent.

**Comment by kmpaul** [comment]
Thanks, @martindurant!  I appreciate it.  I have not had time to do any development these days.

**Comment by martindurant** [comment]
Superseded in #624

**Pull request closed without merging**
