### PR TITLE
Add DBFS scratch

### PR DESCRIPTION
**Pull request by martindurant**
Start for #495 (completely untested, just for fun)

### CODE REVIEW

**Comment by martindurant** [comment]
@raybellwaves , this is done in sync mode - could be made to match the async stuff in the http module.

**Comment by martindurant** [comment]
cc @nils-braun

**Comment by nils-braun** [comment]
Nice start! Definitely something we can build on :-)

**Comment by nils-braun** [comment]
Thanks for making me a collaborator on this branch, @martindurant. I pushed some linting fixes and added tests using vcr (as we discussed, this is not the best solution but should at least serve as a first iteration). I have also described how to record the test casettes again. 
I have also added some more documentation.

**Comment by martindurant** [comment]
Looks good!
I'd be happy to merge this and continue to iterate.

I was unaware of `@pytest.mark.vcr()`! Perhaps things in gcsfs can be simplified.

A couple of thoughts:
- the test only runs on windows, I didn't see changes in the other envs?
- we should change MANIFEST not to include the recordings in the pypi package, which we want to keep small; indeed, perhaps all test files should be pruned.

**Comment by nils-braun** [comment]
Thanks for the review!
* I added the "pytest-vcr" to the `tox.ini`, which is used for testing on linux (you can see e.g. [here](https://github.com/intake/filesystem_spec/pull/504/checks?check_run_id=1617314228#step:4:89) that the test file is used). In general, the environment for non-windows only contains python and tox, the rest is controlled via the tox file.
* Very good point! Will do so.

**Comment by nils-braun** [comment]
Small update: I just checked the [docu](https://packaging.python.org/guides/using-manifest-in/) and what actually happens when I call `python setup.py sdist`  (or `python setup.py bdist_wheel`). In both cases, the tests and everything in it (including the record files) are already excluded. So I think we do not need to do anything here.

**Comment by martindurant** [comment]
Really? I opened https://github.com/intake/filesystem_spec/pull/512, and the package size before/after seem to differ quite a lot (much of that is docs). 
Maybe I am not surprised by the yaml files not being picked up... so perhaps you are right and this is not an issue.

**Comment by martindurant** [comment]
> seem to differ quite a lot

correction: only the sdist; so maybe it was indeed due to docs alone.

**Comment by nils-braun** [comment]
@martindurant - did you had the time to check again the sdist size issue?
If not, from my side we would be ready to merge as a first iteration. Is there some documentation that I should add somewhere?

**Comment by martindurant** [comment]
> did you had the time to check again the sdist size issue?

I'm not bothered in the end, specially since you are definitely *not* adding the yamls here. I was waiting for you to convert from draft PR. Looking again now.

**Comment by martindurant** [comment]
To do on the next iteration: add to API docs under Built-in Implementations, and add to changelog.

**Comment by nils-braun** [comment]
> > did you had the time to check again the sdist size issue?
> 
> I'm not bothered in the end, specially since you are definitely *not* adding the yamls here. I was waiting for you to convert from draft PR. Looking again now.

Ah sorry, yes that is correct. Did not know I can also do this. Thanks!

**Comment by raybellwaves** [comment]
Thanks for this @martindurant and @nils-braun !

**Comment by raybellwaves** [comment]
Just learned about this as an FYI: https://github.com/DataThirstLtd/DBFS-Explorer

**Comment by martindurant** [comment]
Interesting - two years old and untouched since. I wonder if anyone uses fsspec's GUI?

**Comment by raybellwaves** [comment]
TIL! https://github.com/intake/filesystem_spec/blob/master/fsspec/gui.py

**Comment by martindurant** [comment]
https://filesystem-spec.readthedocs.io/en/latest/features.html#file-selector

**Comment by QuLogic** [comment]
The VCR cassettes here don't appear to be correct, as these tests attempt to connect somewhere and fail when there's no network.

**Comment by QuLogic** [comment]
Ah, that was my mistake, I forgot to install `pytest-vcr`. Sorry for the noise.

**Pull request merged**
